### PR TITLE
Added new button and mouse objects with improved mouse events to supp…

### PR DESCRIPTION
**Pull request by zorilya**
Added new button and mouse objects with improved mouse events to support pressing and holding as separate states, press time recording, and press and release position recording. Added a way to manipulate the sciball with the mouse.

There seem to be a lot of whitespace changes being logged on the diffs which makes reading through what has actually changed a little frustrating. I can only guess and attribute that to atom, as It does seem to occasionally mess with formatting in weird ways for my taste. My apologies for the arduous read anyway.

As far as the opcode definition, that is very much a work in progress and it seems i'm running into problems implementing it to allow proper click and dragging of the sciball rather than the scrolling motion that the ball does. I feel like it would really up the feel of interacting with it and potentially be handy for manipulating other screens in the game.

There is a show_mouse_debug function call on 16376 of the snis_client.c (commented out by default) that will show you what the mouse is up to.

Any comments are of course welcome.
     zorilya

### CODE REVIEW

**Comment by smcameron** [comment]
> There seem to be a lot of whitespace changes being logged on the diffs which makes reading through what has actually changed a little frustrating.

Yeah, that's going to need to be fixed.

**Comment by smcameron** [comment]
Mostly it seems to have unceremoniously deleted trailing whitespace wherever it existed.

**Comment by smcameron** [comment]
This seems to be the patch without the whitespace changes:

[add-support-for-mouse-press-and-hold-on-sciball.txt](https://github.com/smcameron/space-nerds-in-space/files/1586567/add-support-for-mouse-press-and-hold-on-sciball.txt)

There are still some formatting problems:

stg show | ./checkpatch.pl -
ERROR: space required after that ',' (ctx:VxV)
#46: FILE: snis_client.c:2743:
+	int x,y;
 	     ^

ERROR: space required after that ',' (ctx:VxV)
#66: FILE: snis_client.c:3381:
+		gettimeofday(&time_now,NULL);
 		                      ^

ERROR: that open brace { should be on the previous line
#68: FILE: snis_client.c:3383:
+		if(mouse.button1.state == 1)
+		{

ERROR: space required before the open parenthesis '('
#68: FILE: snis_client.c:3383:
+		if(mouse.button1.state == 1)

ERROR: space prohibited after that open parenthesis '('
#70: FILE: snis_client.c:3385:
+			if(timeval_difference( mouse.button1.time_pressed, time_now) > BUTTON_HOLD_INTERVAL)

ERROR: space required before the open parenthesis '('
#70: FILE: snis_client.c:3385:
+			if(timeval_difference( mouse.button1.time_pressed, time_now) > BUTTON_HOLD_INTERVAL)

ERROR: that open brace { should be on the previous line
#73: FILE: snis_client.c:3388:
+		if(mouse.button2.state == 1)
+		{

ERROR: space required before the open parenthesis '('
#73: FILE: snis_client.c:3388:
+		if(mouse.button2.state == 1)

ERROR: space prohibited after that open parenthesis '('
#75: FILE: snis_client.c:3390:
+			if(timeval_difference( mouse.button2.time_pressed, time_now) > BUTTON_HOLD_INTERVAL)

ERROR: space required before the open parenthesis '('
#75: FILE: snis_client.c:3390:
+			if(timeval_difference( mouse.button2.time_pressed, time_now) > BUTTON_HOLD_INTERVAL)

ERROR: that open brace { should be on the previous line
#78: FILE: snis_client.c:3393:
+		if(mouse.button3.state == 1)
+		{

ERROR: space required before the open parenthesis '('
#78: FILE: snis_client.c:3393:
+		if(mouse.button3.state == 1)

ERROR: space prohibited after that open parenthesis '('
#80: FILE: snis_client.c:3395:
+			if(timeval_difference( mouse.button3.time_pressed, time_now) > BUTTON_HOLD_INTERVAL)

ERROR: space required before the open parenthesis '('
#80: FILE: snis_client.c:3395:
+			if(timeval_difference( mouse.button3.time_pressed, time_now) > BUTTON_HOLD_INTERVAL)

ERROR: space required before the open parenthesis '('
#84: FILE: snis_client.c:3399:
+		if(mouse.button1.state == 2)

ERROR: space required before the open parenthesis '('
#87: FILE: snis_client.c:3402:
+		if(mouse.button2.state == 2)

ERROR: space required before the open parenthesis '('
#90: FILE: snis_client.c:3405:
+		if(mouse.button3.state == 2)

ERROR: space required after that ',' (ctx:VxV)
#106: FILE: snis_client.c:11057:
+		mouse.button1.state,(int) mouse.button1.press_x,(int) mouse.button1.press_y,
 		                   ^

ERROR: space required after that ',' (ctx:VxV)
#106: FILE: snis_client.c:11057:
+		mouse.button1.state,(int) mouse.button1.press_x,(int) mouse.button1.press_y,
 		                                               ^

ERROR: space required after that ',' (ctx:VxV)
#107: FILE: snis_client.c:11058:
+		(int) mouse.button1.release_x,(int) mouse.button1.release_y);
 		                             ^

ERROR: space required after that ',' (ctx:VxV)
#110: FILE: snis_client.c:11061:
+		mouse.button2.state,(int) mouse.button2.press_x,(int) mouse.button2.press_y,
 		                   ^

ERROR: space required after that ',' (ctx:VxV)
#110: FILE: snis_client.c:11061:
+		mouse.button2.state,(int) mouse.button2.press_x,(int) mouse.button2.press_y,
 		                                               ^

ERROR: space required after that ',' (ctx:VxV)
#111: FILE: snis_client.c:11062:
+		(int) mouse.button2.release_x,(int) mouse.button2.release_y);
 		                             ^

ERROR: space required after that ',' (ctx:VxV)
#114: FILE: snis_client.c:11065:
+		mouse.button3.state,(int) mouse.button3.press_x,(int) mouse.button3.press_y,
 		                   ^

ERROR: space required after that ',' (ctx:VxV)
#114: FILE: snis_client.c:11065:
+		mouse.button3.state,(int) mouse.button3.press_x,(int) mouse.button3.press_y,
 		                                               ^

ERROR: space required after that ',' (ctx:VxV)
#115: FILE: snis_client.c:11066:
+		(int) mouse.button3.release_x,(int) mouse.button3.release_y);
 		                             ^

ERROR: space required after that ',' (ctx:VxV)
#117: FILE: snis_client.c:11068:
+	snprintf(debug_buffer, sizeof(debug_buffer), "Mouse x,y: %d,%d", mouse.x,mouse.y);
 	                                                                        ^

ERROR: space required after that ',' (ctx:VxV)
#129: FILE: snis_client.c:12858:
+	float dxi,dyi,angle,abs_angle,octant;
 	         ^

ERROR: space required after that ',' (ctx:VxV)
#129: FILE: snis_client.c:12858:
+	float dxi,dyi,angle,abs_angle,octant;
 	             ^

ERROR: space required after that ',' (ctx:VxV)
#129: FILE: snis_client.c:12858:
+	float dxi,dyi,angle,abs_angle,octant;
 	                   ^

ERROR: space required after that ',' (ctx:VxV)
#129: FILE: snis_client.c:12858:
+	float dxi,dyi,angle,abs_angle,octant;
 	                             ^

ERROR: space required before the open brace '{'
#142: FILE: snis_client.c:12871:
+	if (dist_from_center < SCIENCE_SCOPE_R){

ERROR: space required before the open brace '{'
#145: FILE: snis_client.c:12874:
+		if(dist_from_center > SCIENCE_SCOPE_R / 10){

ERROR: space required before the open parenthesis '('
#145: FILE: snis_client.c:12874:
+		if(dist_from_center > SCIENCE_SCOPE_R / 10){

WARNING: line over 120 characters
#151: FILE: snis_client.c:12880:
+			/* round the values to create numbers that support the sciball input convention 0 yaw left 1 yaw right*/

ERROR: space required after that ',' (ctx:VxV)
#156: FILE: snis_client.c:12885:
+			angle = (float) atan2(scaled_dy,scaled_dx); /*pointing eastward*/
 			                               ^

WARNING: line over 120 characters
#158: FILE: snis_client.c:12887:
+			octant = PI/8; /* calculate the value we use to create something similar to a D-pad overlaying the ball.*/

ERROR: space required before the open parenthesis '('
#161: FILE: snis_client.c:12890:
+			if(abs_angle > 3 * octant && abs_angle < 5 * octant)

ERROR: space required before the open parenthesis '('
#164: FILE: snis_client.c:12893:
+			if(abs_angle < octant || abs_angle > 7 * octant)

ERROR: space required before the open parenthesis '('
#168: FILE: snis_client.c:12897:
+			if(fabs(scaled_dx) < 0.33 && dxi >= 0)

ERROR: space required before the open parenthesis '('
#171: FILE: snis_client.c:12900:
+			if(fabs(scaled_dy) < 0.33 && dyi >= 0)

ERROR: space required before the open parenthesis '('
#184: FILE: snis_client.c:12913:
+			if(dxi >= 0)

ERROR: space required before the open parenthesis '('
#187: FILE: snis_client.c:12916:
+			if(dyi >= 0)

ERROR: switch and case should be at the same indent
#211: FILE: snis_client.c:12973:
+	switch(button) {
+		case 1:
[...]
+		case 2:
[...]
+		case 3:
[...]
+		default:

ERROR: space required before the open parenthesis '('
#211: FILE: snis_client.c:12973:
+	switch(button) {

ERROR: space required before the open brace '{'
#213: FILE: snis_client.c:12975:
+			if (sci_ui.details_mode == SCI_DETAILS_MODE_THREED){

ERROR: switch and case should be at the same indent
#264: FILE: snis_client.c:17078:
+	switch (event->button) {
+		case 1:
[...]
+		case 2:
[...]
+		case 3:

ERROR: space prohibited after that open parenthesis '('
#267: FILE: snis_client.c:17081:
+			gettimeofday( &(mouse.button1.time_pressed), NULL);

ERROR: space prohibited after that open parenthesis '('
#273: FILE: snis_client.c:17087:
+			gettimeofday( &(mouse.button2.time_pressed), NULL);

ERROR: space prohibited after that open parenthesis '('
#279: FILE: snis_client.c:17093:
+			gettimeofday( &(mouse.button3.time_pressed), NULL);

ERROR: switch and case should be at the same indent
#292: FILE: snis_client.c:17113:
+	switch (event->button) {
+		case 1:
[...]
+		case 2:
[...]
+		case 3:

ERROR: switch and case should be at the same indent
#324: FILE: snis_client.c:17201:
+	switch (displaymode) {
+		case DISPLAYMODE_DEMON:
[...]
+		case DISPLAYMODE_WEAPONS:
[...]
+		case DISPLAYMODE_ENGINEERING:
[...]
+		case DISPLAYMODE_SCIENCE:
[...]
+		default:

ERROR: space prohibited after that open parenthesis '('
#332: FILE: snis_client.c:17209:
+			science_button_held( button, sx, sy);

ERROR: space required after that ',' (ctx:VxV)
#391: FILE: snis_server.c:6851:
+static void set_player_sciball_orientation(struct snis_entity *o,float x, float y)
                                                                 ^

WARNING: line over 120 characters
#474: FILE: snis_server.c:17383:
+		simulate_slow_server(0); /* This being set to zero doesn't seem to do anything... it still simulates running slowly */

total: 52 errors, 3 warnings, 427 lines checked

Your patch has style problems, please review.

If any of these errors are false positives, please ignore them
or fix the script.

**Comment by smcameron** [comment]
Also, running with this patch, the way the mouse interacts with the sciball seems backwards (compared to say, how it behaves running:

```
mesh_viewer -p share/snis/textures/planet-texture0-
```

Haven't dug in far enough to know why yet.

**Comment by smcameron** [comment]
All those criticisms aside, this patch is probably on the right track. Will look into cleaning it up a bit tomorrow.

Thanks!

**Comment by smcameron** [comment]
Ok, here is a patch that has all the things that checkpatch.pl complains about fixed:

[add-support-for-mouse-press-and-hold-on-sciball.txt](https://github.com/smcameron/space-nerds-in-space/files/1587480/add-support-for-mouse-press-and-hold-on-sciball.txt)

I also removed a couple of comments that were not related to what the patch does (about a random seed question, and the simulated_slow_server(0) question.)

A couple more comments:

```
+struct mouse_button {
+       int state; /* Pressed: 1, Released: -1, no activity: 0 */
+       struct timeval time_pressed;
+       double press_x, press_y;
+       double release_x, release_y;
+};
+
+static struct mouse {
+       int x, y;
+       struct mouse_button button1, button2, button3;
+} mouse;
+
```

It strikes me that button1, button2, button3 could be replaced with an array, button[3], and that this could eliminate some of the switch statements in the patch.

Also, I am wondering if GTK has a native way to support drag events that we could use, rather than tracking the timing and button press/release ourselves. It may be that attempting to do that breaks our current method of doing mouse button press/release, I'm not sure. Have you thought about that already?

For example,

GDK_BUTTON_MOTION_MASK     
GDK_BUTTON1_MOTION_MASK    
GDK_BUTTON2_MOTION_MASK    
GDK_BUTTON3_MOTION_MASK 

signals as described here https://developer.gnome.org/gtk-tutorial/stable/x2431.html may be of interest, i.e. use gtk_widget_add_events() and g_signal_connect() in setup_gtk_window_and_drawing_area in snis_client.c to get these events and setup callbacks, rather than trying to track the mouse drag events ourself.  What do you think?

Finally, can you take a look here: https://github.com/smcameron/space-nerds-in-space/blob/master/CONTRIBUTING.md and read item 12 at the bottom (developer's certificate of origin) and indicate if you agree with those terms (mainly, it's asking you to indicate that you do have the right to submit the code, e.g. it's not owned by your employer, or if it is, that you still have the right to submit it, etc.)

Thanks.

**Comment by smcameron** [comment]
Playing around with this a bit more, I realized I misunderstood how it was meant to work -- it's "click and hold" not "click and drag" -- and it really works quite nicely.

**Comment by smcameron** [comment]
Ok, I have some follow on patches that clean this up to my satisfaction, so I would like to commit your change in the following form:

[add-support-for-mouse-press-and-hold-on-sciball.txt](https://github.com/smcameron/space-nerds-in-space/files/1588670/add-support-for-mouse-press-and-hold-on-sciball.txt)

Notice that I added a "Signed-off-by:" line in the patch description for you, which indicates you agree with 
item 12 at the bottom of this page: https://github.com/smcameron/space-nerds-in-space/blob/master/CONTRIBUTING.md

I need you to respond that you do agree before I can commit this though.

And thanks again.

**Comment by zorilya** [comment]
I try and look into the whitespace thing with Atom... I'm intrigued as to what is throwing all the whitespace errors you listed so I can run my code through it also. I guess the convention for writing a lot more specific that I thought.

There is a section which inverts the input values from the mouse to create movement towards the center as opposed to away from the center. search for "dxi -=" in the snis_client.c.

The GTK masks I didn't get around to really sifting through but you're right, they seem to be tracking almost the same info. I'll see what I can do about using them instead to to not be wasting performance.

My ineptitude with C meant that My initial intent (Click and drag in the form of the opcode 194 function) crashed the server so I tried to use what was already available to achieve something more user friendly than the key presses. I will continue to looko into it as a solution because I think it would translate into some of the other stations as a means of control too...

Lastly... I don't work for anyone who would claim this code. It is entirely my work and I give it freely to the project in exchange for credit for my contributions and to see the depth in the back end of this game brought to the front end for the end user to enjoy.

Thanks for the feedback. 
     zorilya

**Comment by smcameron** [comment]
Thanks! I'll make some commits shortly.

I think atom probably (by default, or by some extension) is removing trailing whitespace when you save. There's probably some way to make it not do that, but I don't know what it is.

A bit of a pain in the ass, but not a big deal, as "git diff -b" after applying your patch suppresses whitespace-only diffs, so I can generate a new patch that way. There's a script in the space nerds in space code called "checkpatch.pl", and you can run your change through that, e.g. "git diff | ./checkpatch.pl -", and it will show you all the nitpicky style things that it doesn't like.

I think more significant changes would be needed to make click-and-drag work vs. click-and-hold. The weapons screen tracks mouse motion and makes the guns follow, so I suppose it would have to be something along the lines of how that works. If you go on the demon screen, and click "network stats", you can see that the bandwidth usage from client to server spikes whenever the weapons screen is used (though not really all that much) -- which is one reason I haven't pursued a click-and-drag type interface. I think the click-and-hold interface is miles better than what I had before though, and once I understood it, it didn't really seem backwards, so I think it's fine as it is.

**Comment by smcameron** [comment]
Ok, I have committed this as 7e82794a9c24b7a5ef638d20c4b97a83d07db755 along with a few subsequent commits to clean a few things up.  Thanks again.

**Pull request closed without merging**
