### PR TITLE
modify snis_launcher, ENABLE_ENSCRIPT does not work with long options

### PR DESCRIPTION
**Pull request by spaceshipoperator**
changed ENABLE_ENSCRIPT to specify short option (as long option was not working)

I'm sure there is a more appropriate and complete solution for this; this PR simply demonstrates the problem (and a quick workaround for me so that I can start creating mission scripts) 

Signed-off-by: Brian Muckian <bmuckian@gmail.com>

### CODE REVIEW

**Comment by smcameron** [comment]
Hmm, I just tried enscript with the long option and it worked on my system.  That is to say, I edited snis_launcher and changed it like so:

```
diff --git a/snis_launcher b/snis_launcher
index d683d6fb..b858ff27 100755
--- a/snis_launcher
+++ b/snis_launcher
@@ -34,8 +34,8 @@ SPLASH_SCREEN="ENABLED"
 NO_TEXTURES=
 # NO_TEXTURES=--no-textures
 
-ENABLE_ENSCRIPT=
-# ENABLE_ENSCRIPT=--enable-enscript
+# ENABLE_ENSCRIPT=
+ENABLE_ENSCRIPT=--enable-enscript
 
 if [ "$ASPECT_RATIO" != "" ]
 then
```

and then I was able to use "enscript abc" on the DEMON screen and it saved things in "share/snis/luascripts/ABC"  (I should have saved in ABC.LUA, but it did save it.

I'm not doubting that you encountered a problem, but I don't think we have figured out exactly what the problem is yet.

**Comment by smcameron** [comment]
I have made the following commit:

* 667bf209c4dffd1cf4f455267e6b94fd02eb1a68 snis_launcher: allow setting enable enscript option from options menu 

which allows you to turn on the --enable-enscript option from snis_launcher, via the Options menu (9).

See if that works for you.

**Comment by spaceshipoperator** [comment]
okay...I've been able to enscript, found I had to do two things; in addition to choosing "enable enscript" from the "options"; launch the lobby and then...

First to get contents to get written to my `snis_server_log.txt` I had to launch `3` (snis_server) before `2` (multiverse).  And then, I had to make sure I selected "default" as the solar system to launch my wombat...and then...voila...anyhow I can enscript now...

second star to the right, straight on 'til morning

**Comment by smcameron** [comment]
Committed the following:

* c6f52062a4be7bead691db27c4eba7e18db60b98 snis_launcher: Report unexpected lock dirs

**Pull request closed without merging**
