### PR TITLE
Debian packaging clean-ups

### PR DESCRIPTION
**Pull request by paddatrapper**
Cleans up the Debian packaging a bit:

* Bumps it to the latest policy version
* Adds a watch file for when there are stable releases to track
* Adds missing copyright
* Drops SSL dependency, which was not used and was incompatible with the GPL-2+ - https://people.gnome.org/~markmc/openssl-and-the-gpl.html

There are more lintian errors and warnings that should be fixed, but they are not very urgent. I will be happy to maintain this in Debian once it reaches the point of stable releases.

### CODE REVIEW

**Comment by smcameron** [comment]
Thanks.

Hmm, I noticed that the license text for CC-BY-SA-3.0 that you put into debian/copyright is not quite the same as what's here: https://creativecommons.org/licenses/by-sa/3.0/us/legalcode

And now I'm not sure which one is this one: https://github.com/smcameron/space-nerds-in-space/blob/master/CC-BY-SA.txt -- but in any case in share/snis/Attribution.txt I think are most of the references to CC-BY-SA-3.0

I suspect CC-BY-SA.txt contains the wrong version.

**Comment by smcameron** [comment]
I accepted the commits other than the debian/copyright one due to the discrepancy mentioned above.

**Comment by paddatrapper** [comment]
Yeah, I pulled it from the text file. Will update debian/copyright and the text file tomorrow then

**Comment by paddatrapper** [comment]
Fixed both the text file and debian/copyright

**Comment by smcameron** [comment]
Squashed the latest patch together with the remaining patch to make a single patch and committed.

**Pull request closed without merging**
