### PR TITLE
Engineering presets improvements

### PR DESCRIPTION
**Pull request by MCMic**
- [x] Add back default presets
- [x] Fix lifesupport init
- [x] Add keyboard support
- [x] Fix arduino support

WIP, do not merge yet.

@smcameron The last commit is crashing my snis client at startup with a segfault, I cant figure out what I did wrong?

Also, if I uncomment my lines in deal_with_keyboard it wont build because i use eng_ui before it’s defined, what is your preferred way of fixing that? Should I move deal_with_keyboard or eng_ui or is there a better solution?

### CODE REVIEW

**Comment by smcameron** [comment]
Ok, I reproduced the crash (make mostly-clean; make O=0; ulimit -c unlimited) got a core file...

```
$ gdb -c core bin/snis_client
[...]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./bin/snis_client --lobbyhost localhost --fullscreen'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000044f04e in mapkey (displaymodes=8, keysym=65457, key=key_eng_preset_1) at snis_keyboard.c:227
227				keymap[i][keysym] = key; /* map key on this station */
[Current thread is 1 (Thread 0x7fd93cb2ba00 (LWP 26082))]
(gdb) bt
#0  0x000000000044f04e in mapkey (displaymodes=8, keysym=65457, key=key_eng_preset_1) at snis_keyboard.c:227
#1  0x000000000044f95a in init_keymap () at snis_keyboard.c:362
#2  0x00000000004bd077 in main (argc=4, argv=0x7ffc8631a5d8) at snis_client.c:22845
(gdb) list
222	{
223		int i;
224	
225		for (i = 0; i < DISPLAYMODE_COUNT; i++) {
226			if (displaymodes & (0x1 << i))
227				keymap[i][keysym] = key; /* map key on this station */
228			else
229				continue;
230		}
231	}
(gdb) print i
$1 = 3
(gdb) print key_sym
No symbol "key_sym" in current context.
(gdb) print keysym
$2 = 65457
(gdb)
```

That 65457 doesn't look right considering this in snis_keyboard.h

```
#define DISPLAYMODE_COUNT 14
extern enum keyaction keymap[DISPLAYMODE_COUNT][256];
extern enum keyaction ffkeymap[DISPLAYMODE_COUNT][256];
extern struct keyboard_state kbstate;
```

64457 in hex is 0xFFB1

I think you need to use ffmapkey() instead of mapkey(). for the GDK_KP_* ones.

As for the eng_ui, just move it up before the first usage. Probably I should make a header file to declare all those UI screen types some day.

**Comment by MCMic** [comment]
What is ffmapkey?

**Comment by smcameron** [comment]
ffkeymap() is a terrible hack. :)

If you look in /usr/include/gtk-2.0/gdk/gdkkeysyms.h, you'll see a bunch of 16 bit numbers for keys. (Actually, now that I look, they can be 32 bit numbers, but the vast majority only use the lower 16 bits.)

Most "normal" keys are of the form with 0x00xx. Then there are a bunch of keys that are 0xXXYY where XX is often ff, but sometimes other stuff, and even some that use 32 bits.

keymap[] is the key mapping for all the "normal" keys with 0x00xx form.  mapkey() changes keymap[].  There is also ffkeymap[], which is the mapping for keys that do not fit in 8 bits. I did this by just masking out everything but the low 8 bits.  So I can distinguish between "normal" keys and the "non-normal" keys by checking if if any bits in 8-31 are set, but there can be aliasing among the non-normal keys, because I throw the information in bits 8-31 away.  The function called key_press_cb() in snis_client.c is where this crime occurs.

To fix this properly, I suppose I would need to move away from the simple array indexing scheme and use a hash map or something because the keysym space is too big to use directly as an array index (the array would need to be 4GB or so.) But for your purposes, this hack should work... probably.  Unless you bump into something because of a French keyboard, I suppose.

**Comment by MCMic** [comment]
@smcameron good for merging! (You may want to look at the arduino commit, I did not test it as I do not have an arduino setup)

**Comment by smcameron** [comment]
Ok, I put them in.  Thanks.

As for the arduino, I haven't got the hardware built, so I can't really test it, but it looks ok.  My design allows for 32 inputs (potentiometers and switches), and engineering had 26 and you've added 5 new buttons to engineering for a total of 31.  So we can put 1 more button engineering before my hardware design will be insufficient.

**Comment by smcameron** [comment]
I'm going to close this pull request as all the changes here have been incorporated.

**Comment by smcameron** [comment]
I made some changes to allow buttons to respond differently to a long press, and now you can save engineering presets via a long-press.  This means if you want to make a new preset, you don't have to select an empty one and then set everything, then save it.  Instead, you can tweak the values on the current preset (without saving) then long press on a different preset, and the new values will be saved in the different preset.  So it's easier to make a new preset.  The save button still works as before.

* cf41f4e029d29d70ac78698a2fb080e659778cfe  Rename misleading button press functions 
* c8b7bd8dba506c21029564889b55e39eec66999a  Allow buttons to respond differently to a long press 
* 07e90d65b0ac681c37f58dff827345949b4ec0f2  Allow engineering presets to be saved via long press

**Pull request closed without merging**
