### PR TITLE
SNIS_Commander is a web interface to send commands

### PR DESCRIPTION
**Pull request by spaceshipoperator**
no changes to existing files, just added a very minimal .ipynb

in a python virtualenv with `viola` available you can:

```
 voila --debug --Voila.ip=0.0.0.0 --port 9996 ./SNIS_Commander.ipynb
```

which will serve a very rudimentary web application with a simple form which sends commands to "ship" (natural-language-fifo), "game" (demon mode) and messages which will be read by the computer (text-to-speech) 

Signed-off-by: bmuckian@gmail.com

### CODE REVIEW

**Comment by smcameron** [comment]
Hi, and thanks!

I'm not familiar with voila, and only sorta familiar with python.  Also, there's a few different commits in this pull request, but I suspect you only mean to include the one that adds the SNIS_Commander.ipynb file, is that correct?

So, my inclination for this kind of add-on is to create a "Contrib" subdirectory, and put SNIS_Commander.ipynb in there, maybe in it's own subdirectory of Contrib, with a README that is basically your pull request description.  How does that sound?

**Comment by smcameron** [comment]
After thinking a bit more, I went ahead and committed your change in Contrib, on the theory that it can always be changed later if that is not satisfactory for whatever reason.

* 7d03c9194318055796b8cd3ee758360b87369b6c Add Contrib directory
* b3c3d563c84ec2aed90a74f372d97a7ad8773717 Add SNIS Commander utility

**Comment by spaceshipoperator** [comment]
very cool (and thank you for patience/tolerance for my sloppy PR); I very much like Contrib; I will consider more possibilities there; the "SNIS Commander" is definitely something I will use: pull it up on my phone while playing on N workstations; to do stuff like pause the game, which I only just discovered about a week ago, or tell the ship to go somewhere, do something...I think super useful, hopefully others will too; thank you again 🙏

**Comment by smcameron** [comment]
You're welcome, and thanks for the contribution!

**Pull request closed without merging**
